### ISSUE TITLE
levels: givexp error

### ISSUE THREAD

**Issue by mikeshardmind** [Liante-0216/Liante-Cogs#2]
Seems you are missing an await on a couple coros:

Usage with error: `[p]lvladmin member givexp TestUser 100`

Full traceback:

```py
Exception in command 'lvladmin member givexp'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/cogs/CogManager/cogs/levels/levels.py", line 605, in give_xp
    count = await self._give_xp(member_data=member_data, member=member, exp=xp)
  File "/root/.local/share/Red-DiscordBot/cogs/CogManager/cogs/levels/levels.py", line 309, in _give_xp
    while member_data.get_raw(self.EXP) >= member_data.get_raw(self.GOAL):
TypeError: '>=' not supported between instances of 'coroutine' and 'coroutine'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/commands/commands.py", line 159, in invoke
    await super().invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 927, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/commands/commands.py", line 159, in invoke
    await super().invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 927, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 514, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: '>=' not supported between instances of 'coroutine' and 'coroutine'
```

**Comment by Liante-0216** [comment]
Thank you, this should be fixed now with the latest two commits.
